### ISSUE TITLE
training time

### ISSUE THREAD

**Issue by zhyanlin** [hit-computer/MTA-LSTM#4]
Hi,
I read your paper a few weeks ago, it is a brilliant idea. I'd like to train a model with the dataset you provided. But my computing power is limited. Could you suggest how long it takes when you performed it and the platform (#gpus, or #cpus, and memory) you were working with?
Thanks!

**Comment by hit-computer** [comment]
@cityCoder GPU: T40, CPU: we don't use cpu to training model. Using gpu, need about 4 days for training model

**Comment by zhyanlin** [comment]
thanks

**Comment by Jens0306** [comment]
@cityCoder the data link is no longer available.
Can you send me the dataset you downloaded, plz?

**Comment by zhyanlin** [comment]
I did not access the data before.

**Comment by Jens0306** [comment]
@cityCoder so you didn't train the model before?

**Comment by zhyanlin** [comment]
I have a homemade dataset.
